jobs:

######################### NATIVE WAR CI/CD JOBS #########################

# runCI job that builds and pushes artifact to S3
  - name: shippable-experiments_runCI
    type: runCI
    steps:
      - OUT: demo_s3_file


# runCLI job that deploys artifact in S3 to EC2 - PROD
# based on previous deployment to TEST environment
  - name: demo_s3_prod_deploy
    type: runCLI
    steps:
      - IN: shippable-experiments_runCI
        switch: off
      - IN: demo_s3_file
        switch: off
      - IN: demo_s3_awscli
      - TASK:
        - script: echo "Hey!"
